<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Learning2Test_Logic\Learning2Test_Models.csproj" />
    <ProjectReference Include="..\Learning2Test_DAL\Learning2Test_DAL.csproj" />
  </ItemGroup>

</Project>